Repository bitRocket-dev/startuppario, pull requests merged in 2022-11, with the labels that each got.

#12 fix(general): changed tag elemnets uncorrect
  components/Navbar.tsx
  pages/[title].tsx
  pages/index.tsx
Labels: BUG

#16 feat(general): added title seo into link a
  components/PoweredBy.tsx
  pages/[title].tsx
  pages/index.tsx
Labels: FEAT

#19 doc(config): add github workflow
  .github/workflows/commitlint.yml
  .github/workflows/prettier.yml
Labels: DOC

#21 Fixed tag link
  pages/index.tsx
Labels: BUG

#22 Implemented code controls
  .commitlintrc.json
  .eslintrc.json
  .husky/.gitignore
  .husky/commit-msg
  .husky/common.sh
  .husky/pre-commit
  package.json
  pages/index.tsx
  yarn.lock
Labels: CONFIG

#23 changed ui home
  components/Navbar.tsx
  pages/index.tsx
Labels: FEAT

#20 Feat/theme
  components/Navbar.tsx
  components/PoweredBy.tsx
  components/ToggleTheme.tsx
  index.d.ts
  package.json
  pages/[title].tsx
  pages/_app.tsx
  pages/index.tsx
  styles/ViewStartuppario.module.css
  styles/globals.css
  theme/ThemeProvider.tsx
  theme/general/mapColors.ts
  utility/utilityGetTheme.ts
  yarn.lock
Labels: FEAT

#32 Changed UI Detail
  components/PoweredBy.tsx
  components/ToggleTheme.tsx
  index.d.ts
  pages/[title].tsx
  pages/index.tsx
  theme/general/mapColors.ts
Labels: FEAT

#35 feat(general): added robots.txt file
  public/robots.txt
Labels: FEAT

#38 feat(config): added lang attribute
  pages/_document.tsx
  tsconfig.json
  yarn.lock
Labels: CONFIG

#40 Corretti problemi SEO e Best Practices
  components/Navbar.tsx
  pages/index.tsx
Labels: SEO

#43 Corretto Next link
  pages/index.tsx
Labels: BUG

#48 Fix/json api
  .gitignore
  constants/general.ts
  declaration/general.ts
  package.json
  pages/[title].tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/api/[title].ts
  pages/api/apiWordDetail.tsx
  pages/api/apiWordList.tsx
  pages/api/hello.ts
  pages/api/requestTitleList.ts
  pages/events/index.tsx
  pages/index.tsx
  tsconfig.json
  utils/getTheme.ts
  utils/setQuery.ts
Labels: BUG

#49 Removed duplicated on json and changed replaceAll
  json/startuppario.json
  pages/index.tsx
Labels: BUG

#50 utility get theme can return null now
  utils/getTheme.ts
Labels: BUG
